const COLORS=['red','green','yellow','blue'];
const NAMES=['Red','Green','Yellow','Blue'];
const ICONS=['🔴','🟢','🟡','🔵'];
const STARTS=[0,13,26,39];
const FINISH=57;
const PATH=[[6,1],[6,2],[6,3],[6,4],[6,5],[5,6],[4,6],[3,6],[2,6],[1,6],[0,6],[0,7],[0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,9],[6,10],[6,11],[6,12],[6,13],[6,14],[7,14],[8,14],[8,13],[8,12],[8,11],[8,10],[8,9],[9,8],[10,8],[11,8],[12,8],[13,8],[14,8],[14,7],[14,6],[13,6],[12,6],[11,6],[10,6],[9,6],[8,5],[8,4],[8,3],[8,2],[8,1],[8,0],[7,0],[6,0]];
const SPECIALS={5:'boost',12:'warp',18:'bomb',25:'boost',31:'warp',38:'bomb',45:'boost'};
const SAFE=new Set([0,8,13,21,26,34,39,47]);
const EVENTS=[{name:'Chaos Surge',icon:'🌪️',text:'Your next move gets +1.',type:'plus'},{name:'Black Hole',icon:'🕳️',text:'Warp tiles send you +5.',type:'warp'},{name:'Double Dice',icon:'🎲',text:'Roll twice and keep the higher roll.',type:'double'},{name:'Meteor Strike',icon:'☄️',text:'One power tile is disabled this round.',type:'meteor'},{name:'Speed Round',icon:'🔥',text:'Landing on Boost grants another turn.',type:'speed'}];
const state={players:2,current:0,dice:0,rolling:false,turnReady:true,logs:[],tokens:[],winner:null,roundEvent:null};
for(let p=0;p<4;p++)for(let t=0;t<4;t++)state.tokens.push({p,t,pos:-1,done:false});
const app=document.querySelector('#app');
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function loading(){app.innerHTML=`<div class="loading"><div class="loader-logo"><div class="loader-dice">🎲</div><div class="loader-title">LUDO <b>CHAOS</b></div><div class="loader-sub">IT'S LUDO… UNTIL THE BOARD TURNS AGAINST YOU.</div></div><div class="loadbar"><i></i></div><div class="loadhint">Preparing the Chaos board…</div></div>`;setTimeout(render,1500)}
function render(){app.innerHTML=`<div class="game-shell"><header class="topbar"><div class="brand"><div class="brandmark">🎲</div><div><h1>LUDO <span>CHAOS</span></h1><small>Classic Ludo. Unpredictable board.</small></div></div><div class="match-pill">LOCAL • ${state.players} PLAYERS</div></header><main class="game-layout"><section class="game-panel"><div class="turnbar"><div class="turn-player"><i class="turn-dot ${COLORS[state.current]}"></i><strong>${NAMES[state.current]}'s turn</strong><span>• Roll the dice</span></div><div class="score-row">${Array.from({length:state.players},(_,p)=>`<span>${ICONS[p]} <b>${state.tokens.filter(t=>t.p===p&&t.done).length}/4</b></span>`).join('')}</div></div><div class="board-wrap"><div class="board">${buildBoard()}</div></div><div class="roll-area"><button class="dice-btn ${state.rolling?'rolling':''}" id="diceBtn" aria-label="Roll dice"><span>${state.dice||'?'}</span></button><button class="roll-btn" id="roll" ${state.rolling||!state.turnReady?'disabled':''}>ROLL DICE</button></div><div class="tip">Roll a <b>6</b> to bring a token out. Tap a glowing token to move.</div></section><aside class="side-panel"><div class="side-card event-card"><div class="side-head"><h3>${state.roundEvent?'🌪️ CHAOS EVENT':'⚡ CHAOS EVENT'}</h3><span class="live-dot"></span></div><div class="event-content">${state.roundEvent?`<strong>${state.roundEvent.icon} ${state.roundEvent.name}</strong><p>${state.roundEvent.text}</p>`:'Every round can change the rules. Roll to reveal the chaos.'}</div></div><div class="side-card"><h3>GAME MODE</h3><button class="mode-btn" id="mode">${state.players} Players <span>HOT SEAT ›</span></button></div><div class="side-card"><h3>POWER TILES</h3><div class="powers"><div><b class="power-icon boost">⚡</b><span>Boost</span><em>+3</em></div><div><b class="power-icon bomb">💣</b><span>Bomb</span><em>Nearby</em></div><div><b class="power-icon warp">🌀</b><span>Warp</span><em>+5</em></div></div></div><div class="side-card log-card"><h3>MATCH LOG</h3><div class="log">${state.logs.length?state.logs.map(x=>`<div>${x}</div>`).join(''):'<div class="muted">No moves yet.</div>'}</div></div></aside></main>${state.winner?winnerOverlay():''}</div>`;bind()}
function buildBoard(){let out='';for(let r=0;r<15;r++)for(let c=0;c<15;c++){let cls='cell',content='';if(r<6&&c<6){cls+=' yard red-yard';content=yard(0,r,c)}else if(r<6&&c>8){cls+=' yard green-yard';content=yard(1,r,c)}else if(r>8&&c>8){cls+=' yard yellow-yard';content=yard(2,r,c)}else if(r>8&&c<6){cls+=' yard blue-yard';content=yard(3,r,c)}else if(r>=6&&r<=8&&c>=6&&c<=8){cls+=' center';content=(r===7&&c===7)?'<span>CHAOS</span>':''}else{const idx=PATH.findIndex(p=>p[0]===r&&p[1]===c);if(idx>=0){cls+=' track';if(SAFE.has(idx))cls+=' safe';const power=activePower(idx);if(power){cls+=` power ${power}`;content=power==='boost'?'⚡':power==='warp'?'🌀':'💣'}const toks=state.tokens.filter(t=>t.p<state.players&&!t.done&&t.pos>=0&&PATH[(STARTS[t.p]+t.pos)%52]?.[0]===r&&PATH[(STARTS[t.p]+t.pos)%52]?.[1]===c);if(toks.length)content=`<div class="token-stack">${toks.map(t=>`<button class="token ${COLORS[t.p]} ${t.p===state.current&&!state.turnReady&&legal(t)?'movable':''}" data-token="${t.p}-${t.t}" aria-label="${NAMES[t.p]} token ${t.t+1}"></button>`).join('')}</div>`}}out+=`<div class="${cls}">${content}</div>`}return out}
function activePower(i){if(state.roundEvent?.type==='meteor'&&i===state.roundEvent.disabled)return null;return SPECIALS[i]}
function yard(p,r,c){if(p>=state.players)return '';const spots=[[1,1],[1,4],[4,1],[4,4]],i=spots.findIndex(s=>s[0]===r%6&&s[1]===c%6);if(i<0)return '';const t=state.tokens.find(x=>x.p===p&&x.t===i);return t?.pos===-1?`<button class="token ${COLORS[p]} ${p===state.current&&!state.turnReady&&state.dice===6?'movable':''}" data-token="${p}-${i}" aria-label="${NAMES[p]} token ${i+1}"></button>`:''}
function bind(){document.querySelector('#roll').onclick=roll;document.querySelector('#diceBtn').onclick=roll;document.querySelector('#mode').onclick=()=>{state.players=state.players===4?2:state.players+1;reset()};document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>moveToken(b.dataset.token));document.querySelector('.again')?.addEventListener('click',reset)}
function addLog(s){state.logs.unshift(s);state.logs=state.logs.slice(0,8)}
async function roll(){if(state.rolling||!state.turnReady)return;state.rolling=true;state.dice=1;render();for(let i=0;i<10;i++){await sleep(55);state.dice=1+Math.floor(Math.random()*6);render()}let value=state.dice;if(state.roundEvent?.type==='double'){await sleep(180);const second=1+Math.floor(Math.random()*6);value=Math.max(value,second);state.dice=value;addLog(`🎲 Double Dice → ${value}`)}state.rolling=false;state.turnReady=false;state.dice=value;const event=EVENTS[Math.floor(Math.random()*EVENTS.length)];state.roundEvent=event.type==='meteor'?{...event,disabled:Number(Object.keys(SPECIALS)[Math.floor(Math.random()*Object.keys(SPECIALS).length)])}:event;addLog(`${ICONS[state.current]} ${NAMES[state.current]} rolled ${value}.`);render();showMoves()}
function legal(t){return !t.done&&(t.pos===-1?state.dice===6:t.pos+state.dice<=FINISH)}
function showMoves(){const moves=state.tokens.filter(t=>t.p===state.current&&legal(t));if(!moves.length){addLog(`${ICONS[state.current]} No legal move.`);render();setTimeout(nextTurn,700);return}document.querySelectorAll('[data-token]').forEach(b=>{const [p,t]=b.dataset.token.split('-').map(Number);if(p===state.current&&moves.some(x=>x.t===t))b.classList.add('movable')})}
async function moveToken(key){if(state.turnReady)return;const [p,t]=key.split('-').map(Number);if(p!==state.current)return;const tok=state.tokens.find(x=>x.p===p&&x.t===t);if(!tok||!legal(tok))return;const rollValue=state.dice;tok.pos=tok.pos===-1?0:tok.pos+rollValue;render();await sleep(180);const boardIndex=tok.pos<FINISH?(STARTS[p]+tok.pos)%52:null;const power=boardIndex==null?null:activePower(boardIndex);if(power==='boost'){tok.pos=Math.min(FINISH,tok.pos+3);addLog(`${ICONS[p]} ⚡ Boost +3!`);pulse('⚡ BOOST +3')}else if(power==='warp'){tok.pos=Math.min(FINISH,tok.pos+5);addLog(`${ICONS[p]} 🌀 Warp +5!`);pulse('🌀 WARP +5')}else if(power==='bomb'){bomb(tok);pulse('💣 BOMB!')}if(state.roundEvent?.type==='plus'){tok.pos=Math.min(FINISH,tok.pos+1);addLog('🌪️ Chaos Surge +1!')}if(tok.pos===FINISH)tok.done=true;capture(tok);addLog(`${ICONS[p]} ${NAMES[p]} moved ${rollValue}.`);if(state.tokens.filter(x=>x.p===p&&x.done).length===4){state.winner=p;state.dice=0;state.turnReady=true;render();return}const extra=rollValue===6||power==='boost'||state.roundEvent?.type==='speed';state.dice=0;state.turnReady=true;if(!extra)state.current=(state.current+1)%state.players;state.roundEvent=null;render()}
function capture(m){if(m.pos<0||m.done)return;const cell=(STARTS[m.p]+m.pos)%52;if(SAFE.has(cell))return;for(const x of state.tokens)if(x.p!==m.p&&x.p<state.players&&!x.done&&x.pos>=0&&(STARTS[x.p]+x.pos)%52===cell){x.pos=-1;addLog(`💥 ${ICONS[m.p]} captured ${ICONS[x.p]}!`)}}
function bomb(m){const cell=(STARTS[m.p]+m.pos)%52;for(const x of state.tokens)if(x.p!==m.p&&x.p<state.players&&!x.done&&x.pos>=0){const other=(STARTS[x.p]+x.pos)%52;const d=Math.min((cell-other+52)%52,(other-cell+52)%52);if(d<=2)x.pos=-1}}
function nextTurn(){state.dice=0;state.turnReady=true;state.current=(state.current+1)%state.players;state.roundEvent=null;render()}
function pulse(text){const el=document.createElement('div');el.className='power-toast';el.textContent=text;document.body.appendChild(el);setTimeout(()=>el.remove(),850)}
function winnerOverlay(){return `<div class="win"><div class="winbox"><div class="confetti">✦ ✧ ✦</div><div class="trophy">🏆</div><h2>${ICONS[state.winner]} ${NAMES[state.winner]} WINS!</h2><p>All four tokens conquered the Chaos board.</p><button class="again">PLAY AGAIN</button></div></div>`}
function reset(){state.current=0;state.dice=0;state.rolling=false;state.turnReady=true;state.roundEvent=null;state.logs=[];state.winner=null;for(const t of state.tokens){t.pos=-1;t.done=false}render()}
loading();