const COLORS=['red','blue','green','yellow'];
const NAMES=['Crimson','Azure','Emerald','Gold'];
const ICONS=['🔴','🔵','🟢','🟡'];
const STARTS=[0,13,26,39];
const FINISH=52;
const TRACK=[];
for(let c=1;c<14;c++)TRACK.push([6,c]);
for(let r=7;r<14;r++)TRACK.push([r,8]);
for(let c=7;c>=1;c--)TRACK.push([8,c]);
for(let r=7;r>=1;r--)TRACK.push([r,6]);
const unique=[];const seen=new Set();for(const p of TRACK){const k=p.join(',');if(!seen.has(k)){seen.add(k);unique.push(p)}}
const SPECIALS={5:'⚡',12:'🌀',19:'💣',27:'⚡',35:'🌀',43:'💣',49:'⚡'};
const EVENTS=['🌪️ Chaos Surge — your next move gets +1.','🕳️ Black Hole — landing on 🌀 warps you +5.','🎲 Double Dice — roll 2 dice and choose the better result.','☄️ Meteor — one random power tile is disabled this round.','🔥 Speed Round — a ⚡ tile grants an extra turn.'];
const state={players:2,current:0,dice:0,rolling:false,turnReady:true,event:'Welcome to Ludo Chaos. Roll the dice to begin.',logs:[],tokens:[]};
for(let p=0;p<4;p++)for(let t=0;t<4;t++)state.tokens.push({p,t,pos:-1,done:false});
const app=document.querySelector('#app');
function render(){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="brandmark">🎲</div><div><h1>LUDO CHAOS</h1><span>Classic Ludo. Unpredictable board.</span></div></div><div class="pill">LOCAL BATTLE • ${state.players} PLAYERS</div></header><main class="layout"><section class="panel game"><div class="hud"><div class="turn"><i class="dot" style="color:${['#ef5b68','#4f86ff','#4fd39b','#ffd66d'][state.current]}"></i>${NAMES[state.current]}'s turn</div><div class="score">${Array.from({length:state.players},(_,p)=>`<b>${ICONS[p]} ${state.tokens.filter(x=>x.p===p&&x.done).length}/4</b>`).join('')}</div></div><div class="board">${buildBoard()}</div><div class="controls"><div class="dice ${state.rolling?'rolling':''}">${state.dice||'•'}</div><button class="roll" id="roll" ${state.rolling||!state.turnReady?'disabled':''}>ROLL DICE</button></div><div class="foot">Roll a 6 to launch. Click a glowing token to move. Power tiles can change the turn.</div></section><aside class="panel side"><div class="card"><h3>⚡ CHAOS EVENT</h3><div class="eventbox">${state.event}</div></div><div class="card"><h3>MODE</h3><button class="mode" id="mode">${state.players} Players · Hot Seat</button></div><div class="card"><h3>POWER TILES</h3><div class="powerlist"><div class="power"><span>⚡ Boost</span><strong>+3</strong></div><div class="power"><span>💣 Bomb</span><strong>Near capture</strong></div><div class="power"><span>🌀 Warp</span><strong>+5</strong></div></div></div><div class="card"><h3>MATCH LOG</h3><div class="log">${state.logs.length?state.logs.map(x=>`<div>${x}</div>`).join(''):'<div>No moves yet.</div>'}</div></div></aside></main></div>`;bind();}
function buildBoard(){let out='';for(let r=0;r<15;r++)for(let c=0;c<15;c++){const idx=unique.findIndex(p=>p[0]===r&&p[1]===c);let cls='cell',content='';if(idx>=0){cls+=' track';if(SPECIALS[idx]){cls+=' power';content=SPECIALS[idx]}if(idx%13===0){cls+=' safe';content=content||'✦'}const tokens=state.tokens.filter(x=>x.p<state.players&&!x.done&&x.pos>=0&&unique[(STARTS[x.p]+x.pos)%unique.length][0]===r&&unique[(STARTS[x.p]+x.pos)%unique.length][1]===c);if(tokens.length)content=`<div class="token-stack">${tokens.map(x=>`<button class="token ${COLORS[x.p]} ${x.p===state.current&&!state.turnReady?'movable':''}" data-token="${x.p}-${x.t}" aria-label="${NAMES[x.p]} token ${x.t+1}"></button>`).join('')}</div>`}if(r<6&&c<6){cls+=' home red';content=homeTokens(0,r,c)}if(r<6&&c>8){cls+=' home blue';content=homeTokens(1,r,c)}if(r>8&&c<6){cls+=' home green';content=homeTokens(2,r,c)}if(r>8&&c>8){cls+=' home yellow';content=homeTokens(3,r,c)}if(r>=6&&r<=8&&c>=6&&c<=8&&r===7&&c===7){cls='center';content='CHAOS'}out+=`<div class="${cls}">${content}</div>`}return out}
function homeTokens(p,r,c){if(p>=state.players)return '';const spots=[[1,1],[4,1],[1,4],[4,4]],i=spots.findIndex(s=>s[0]===r%6&&s[1]===c%6);if(i<0)return '';const tok=state.tokens.find(x=>x.p===p&&x.t===i);if(!tok||tok.pos!==-1)return '';return `<button class="token ${COLORS[p]} ${p===state.current&&!state.turnReady&&state.dice===6?'movable':''}" data-token="${p}-${i}" aria-label="${NAMES[p]} token ${i+1}"></button>`}
function bind(){document.querySelector('#roll').onclick=roll;document.querySelector('#mode').onclick=()=>{state.players=state.players===4?2:state.players+1;reset()};document.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>moveToken(b.dataset.token));}
function addLog(s){state.logs.unshift(s);state.logs=state.logs.slice(0,9)}
function roll(){if(state.rolling||!state.turnReady)return;state.rolling=true;state.dice=0;render();let ticks=0;const timer=setInterval(()=>{state.dice=1+Math.floor(Math.random()*6);render();ticks++;if(ticks>=8){clearInterval(timer);state.rolling=false;state.turnReady=false;state.event=Math.random()<.45?EVENTS[Math.floor(Math.random()*EVENTS.length)]:`${ICONS[state.current]} ${NAMES[state.current]} rolled ${state.dice}.`;render();showMoves()}},70)}
function legal(t){return !t.done&&(t.pos===-1?state.dice===6:t.pos+state.dice<=FINISH)}
function showMoves(){const moves=state.tokens.filter(t=>t.p===state.current&&legal(t));if(!moves.length){addLog(`${ICONS[state.current]} ${NAMES[state.current]} has no legal move.`);setTimeout(nextTurn,700);return}document.querySelectorAll('[data-token]').forEach(b=>{const [p,t]=b.dataset.token.split('-').map(Number);if(p===state.current&&moves.some(x=>x.t===t))b.classList.add('movable')})}
function moveToken(key){if(state.turnReady)return;const [p,t]=key.split('-').map(Number);if(p!==state.current)return;const tok=state.tokens.find(x=>x.p===p&&x.t===t);if(!tok||!legal(tok))return;const rollValue=state.dice;tok.pos=tok.pos===-1?0:tok.pos+rollValue;let power=tok.pos<FINISH?SPECIALS[(STARTS[p]+tok.pos)%unique.length]:null;if(power==='⚡'){tok.pos=Math.min(FINISH,tok.pos+3);addLog(`${ICONS[p]} Boost! +3 movement.`)}else if(power==='🌀'){tok.pos=Math.min(FINISH,tok.pos+5);addLog(`${ICONS[p]} Warp! +5 movement.`)}else if(power==='💣'){bomb(tok)}if(tok.pos===FINISH)tok.done=true;capture(tok);addLog(`${ICONS[p]} ${NAMES[p]} moved ${rollValue}.`);if(state.tokens.filter(x=>x.p===p&&x.done).length===4){win(p);return}const extra=rollValue===6||power==='⚡';state.dice=0;state.turnReady=true;if(!extra)state.current=(state.current+1)%state.players;state.event=extra?`${NAMES[p]} earned another turn!`:'The board waits for your next roll.';render()}
function capture(m){if(m.pos<0||m.done)return;const cell=(STARTS[m.p]+m.pos)%unique.length;for(const x of state.tokens)if(x.p!==m.p&&x.p<state.players&&!x.done&&x.pos>=0&&(STARTS[x.p]+x.pos)%unique.length===cell){x.pos=-1;addLog(`💥 ${ICONS[m.p]} captured ${ICONS[x.p]}!`)}}
function bomb(m){for(const x of state.tokens)if(x.p!==m.p&&x.p<state.players&&!x.done&&x.pos>=0&&Math.abs(x.pos-m.pos)<=2)x.pos=-1}
function nextTurn(){state.dice=0;state.turnReady=true;state.current=(state.current+1)%state.players;state.event='Chaos is watching. Roll when ready.';render()}
function win(p){app.insertAdjacentHTML('beforeend',`<div class="win"><div class="winbox"><div class="big">🏆</div><h2>${NAMES[p]} WINS!</h2><p>All four tokens conquered the Chaos board.</p><button class="again">PLAY AGAIN</button></div></div>`);document.querySelector('.again').onclick=reset}
function reset(){state.current=0;state.dice=0;state.rolling=false;state.turnReady=true;state.event='Welcome to Ludo Chaos. Roll the dice to begin.';state.logs=[];for(const t of state.tokens){t.pos=-1;t.done=false}render()}
render();
