const COLORS=['red','blue','green','yellow'];
const NAMES=['Crimson','Azure','Emerald','Gold'];
const icons=['🔴','🔵','🟢','🟡'];
const path=[];
for(let r=0;r<15;r++)for(let c=0;c<15;c++){if((r===6||r===8)&&c>0&&c<14|| (c===6||c===8)&&r>0&&r<14)path.push([r,c])}
const unique=[];const seen=new Set();for(const p of path){const k=p.join(',');if(!seen.has(k)){seen.add(k);unique.push(p)}}
const specials={5:'⚡',13:'⚡',21:'💣',31:'🌀',40:'⚡',50:'💣',60:'🌀',69:'⚡',78:'💣',88:'⚡',96:'🌀'};
const events=['🌪️ Chaos Surge: every token gets +1 movement next turn.','🕳️ Black Hole: the next landing on a power tile teleports you forward 5.','🎲 Double Dice: the current player rolls twice and chooses the result.','☄️ Meteor: one random track tile becomes blocked for this round.','🔥 Speed Round: the next successful move grants another turn.'];
const state={players:2,current:0,dice:0,rolling:false,turnReady:true,selected:null,event:'Welcome to Ludo Chaos. Roll the dice to begin.',logs:[],tokens:[]};
for(let p=0;p<4;p++)for(let t=0;t<4;t++)state.tokens.push({p,t,pos:-1,done:false});
const app=document.querySelector('#app');
function html(){app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand"><div class="brandmark">🎲</div><div><h1>LUDO CHAOS</h1><span>Classic Ludo. Unpredictable board.</span></div></div><div class="pill">LOCAL BATTLE • ${state.players} PLAYERS</div></header><main class="layout"><section class="panel game"><div class="hud"><div class="turn"><i class="dot" style="color:${['#ef5b68','#4f86ff','#4fd39b','#ffd66d'][state.current]}"></i>${NAMES[state.current]}'s turn</div><div class="score">${Array.from({length:state.players},(_,p)=>`<b>${icons[p]} ${state.tokens.filter(x=>x.p===p&&x.done).length}/4</b>`).join('')}</div></div><div class="board" id="board">${buildBoard()}</div><div class="controls"><div class="dice ${state.rolling?'rolling':''}" id="dice">${state.dice?state.dice:'•'}</div><button class="roll" id="roll" ${state.rolling||!state.turnReady?'disabled':''}>ROLL DICE</button></div><div class="foot">Click a highlighted token after rolling. Exact 6 launches a token from base.</div></section><aside class="panel side"><div class="card"><h3>⚡ CHAOS EVENT</h3><div class="eventbox">${state.event}</div></div><div class="card"><h3>MODE</h3><button class="mode" id="mode">${state.players} Players · Hot Seat</button></div><div class="card"><h3>POWER TILES</h3><div class="powerlist"><div class="power"><span>⚡ Boost</span><strong>+3</strong></div><div class="power"><span>💣 Bomb</span><strong>Capture nearby</strong></div><div class="power"><span>🌀 Warp</span><strong>Jump +5</strong></div></div></div><div class="card"><h3>MATCH LOG</h3><div class="log">${state.logs.length?state.logs.map(x=>`<div>${x}</div>`).join(''):'<div>No moves yet.</div>'}</div></div></aside></main></div>`;bind();}
function buildBoard(){let cells='';for(let r=0;r<15;r++)for(let c=0;c<15;c++){let cls='cell';let content='';const idx=unique.findIndex(p=>p[0]===r&&p[1]===c);if(idx>=0){cls+=' track';if(specials[idx]){cls+=' power';content=specials[idx]}if(idx%11===0){cls+=' safe';content=content||'✦'}}if(r<6&&c<6){cls+=' home red';content=homeTokens(0,r,c)}if(r<6&&c>8){cls+=' home blue';content=homeTokens(1,r,c)}if(r>8&&c<6){cls+=' home green';content=homeTokens(2,r,c)}if(r>8&&c>8){cls+=' home yellow';content=homeTokens(3,r,c)}if(r>=6&&r<=8&&c>=6&&c<=8&&r===7&&c===7){cls='center';content='CHAOS'}cells+=`<div class="${cls}" data-r="${r}" data-c="${c}">${content}</div>`}return cells}
function homeTokens(p,r,c){if(p>=state.players)return '';const spots=[[1,1],[4,1],[1,4],[4,4]];let i=spots.findIndex(s=>s[0]===r%6&&s[1]===c%6);if(i<0)return '';const tok=state.tokens.find(x=>x.p===p&&x.t===i);return `<button class="token ${COLORS[p]} ${state.selected===`${p}-${i}`?'stack':''}" data-token="${p}-${i}" aria-label="${NAMES[p]} token ${i+1}"></button>`}
function bind(){document.querySelector('#roll').onclick=roll;document.querySelector('#mode').onclick=()=>{state.players=state.players===4?2:state.players+1;reset()};document.querySelectorAll('[data-token]').forEach(b=>b.onclick=e=>moveToken(e.currentTarget.dataset.token));}
function log(s){state.logs.unshift(s);state.logs=state.logs.slice(0,10)}
function roll(){if(state.rolling||!state.turnReady)return;state.rolling=true;state.dice=0;html();let n=0;const timer=setInterval(()=>{state.dice=1+Math.floor(Math.random()*6);html();n++;if(n>=7){clearInterval(timer);state.rolling=false;state.turnReady=false;state.event=Math.random()<.34?events[Math.floor(Math.random()*events.length)]:`Nothing is stable. ${NAMES[state.current]} rolled ${state.dice}.`;state.selected=null;html();highlightMovable()}},75)}
function highlightMovable(){const movable=state.tokens.filter(x=>x.p===state.current&&!x.done&&(x.pos===-1?state.dice===6:true));if(!movable.length){log(`${icons[state.current]} ${NAMES[state.current]} rolled ${state.dice} — no legal move.`);setTimeout(nextTurn,650);return}document.querySelectorAll(`[data-token]`).forEach(b=>{const [p,t]=b.dataset.token.split('-').map(Number);if(p===state.current&&movable.some(x=>x.t===t))b.style.outline='3px solid white'});}
function moveToken(key){if(state.turnReady)return;const [p,t]=key.split('-').map(Number);if(p!==state.current)return;const tok=state.tokens.find(x=>x.p===p&&x.t===t);if(!tok||tok.done)return;if(tok.pos===-1&&state.dice!==6)return;tok.pos=tok.pos===-1?0:tok.pos+state.dice;const finish=state.posToFinish||52;if(tok.pos>=finish){tok.pos=finish;tok.done=true}let power=specials[tok.pos%unique.length];if(power==='⚡'&&!tok.done)tok.pos=Math.min(finish,tok.pos+3);if(power==='🌀'&&!tok.done)tok.pos=Math.min(finish,tok.pos+5);if(power==='💣'&&!tok.done)bomb(tok);capture(tok);log(`${icons[p]} ${NAMES[p]} moved ${state.dice}${power?` and hit ${power}`:''}.`);if(state.tokens.filter(x=>x.p===p&&x.done).length===4){win(p);return}const extra=state.dice===6||power==='⚡';state.turnReady=true;state.dice=0;if(!extra)state.current=(state.current+1)%state.players;state.event=extra?`${NAMES[p]} earned another turn!`:'The board waits for your next roll.';html();}
function capture(m){if(m.pos<0)return;for(const x of state.tokens){if(x.p!==m.p&&x.p<state.players&&!x.done&&x.pos===m.pos){x.pos=-1;log(`💥 ${icons[m.p]} captured ${icons[x.p]}!`);}}}
function bomb(m){for(const x of state.tokens)if(x.p!==m.p&&x.p<state.players&&Math.abs(x.pos-m.pos)<=2)x.pos=-1}
function nextTurn(){state.dice=0;state.turnReady=true;state.current=(state.current+1)%state.players;state.event='Chaos is watching. Roll when ready.';html()}
function win(p){app.insertAdjacentHTML('beforeend',`<div class="win"><div class="winbox"><div class="big">🏆</div><h2>${NAMES[p]} WINS!</h2><p>All four tokens reached the center of chaos.</p><button class="again">PLAY AGAIN</button></div></div>`);document.querySelector('.again').onclick=reset}
function reset(){state.current=0;state.dice=0;state.turnReady=true;state.selected=null;state.logs=[];state.event='Welcome to Ludo Chaos. Roll the dice to begin.';for(const x of state.tokens){x.pos=-1;x.done=false}html()}
html();
